export const UPDATE_ITEMS = "UPDATE_ITEMS";
export const UPDATE_CURRENT_KEYWORD = 'UPDATE_CURRENT_KEYWORD';
export const UPDATE_CURRENT_ITEM = 'UPDATE_CURRENT_ITEM';
export const UPDATE_CURRENT_MODAL = 'UPDATE_CURRENT_MODAL'
export const UPDATE_CURRENT_MODAL_STATE = 'UPDATE_CURRENT_MODAL_STATE'